# Generated by Django 3.2.4 on 2021-10-17 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('o_level', models.CharField(max_length=150)),
                ('a_level', models.CharField(max_length=150)),
                ('diploma', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modifield_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificates',
            },
            managers=[
                ('certificates', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(max_length=150)),
            ],
            options={
                'db_table': 'courses',
            },
            managers=[
                ('courses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('univ_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('univ_name', models.CharField(max_length=150)),
                ('course_id', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'universities',
            },
            managers=[
                ('universities', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Scholar_ship',
            fields=[
                ('scholar_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.university')),
            ],
            options={
                'db_table': 'scholar_ships',
            },
            managers=[
                ('scholar_ships', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Course_price',
            fields=[
                ('price_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_price', models.CharField(max_length=150)),
                ('year_study', models.IntegerField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.university')),
            ],
            options={
                'db_table': 'course_prices',
            },
            managers=[
                ('course_prices', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='apply',
            fields=[
                ('apply_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=150)),
                ('graduation_year', models.CharField(max_length=150)),
                ('result', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modifield_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.certificate')),
            ],
            options={
                'db_table': 'applies',
            },
            managers=[
                ('applies', django.db.models.manager.Manager()),
            ],
        ),
    ]
