# Generated by Django 3.2.4 on 2021-11-02 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_apply_certificate_course_course_price_scholar_ship_university'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users_address',
            new_name='Address',
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.course'),
        ),
    ]
