# Generated by Django 3.2.4 on 2021-11-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_course_id_university_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
